[[pattern]]
name = "Amazon AWS Access Key ID"
regex = "\b(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}\b"

[[pattern]]
name = "Amazon AWS Secret Key"
regex = "aws(.{0,20})?['\\\"][0-9a-zA-Z/+]{40}['\\\"]"

[[pattern]]
name = "Amazon MWS Auth Token"
regex = "amzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"

[[pattern]]
name = "Basic Auth"
regex = "://[a-zA-Z0-9]+:[a-zA-Z0-9]+@[a-zA-Z0-9]+\\.[a-zA-Z]+"

[[pattern]]
name = "Dropbox API secret"
regex = "(?i)(?:dropbox)(?:[0-9a-z\\-_\t .]{0,20})(?:[\\s|']|[\\s|\"]){0,3}(?:=|>|:{1,3}=|\\|\\|:|<=|=>|:|\\?=)(?:'|\"|\\s|=|\\x60){0,5}([a-z0-9]{15})(?:['|\"|\n|\r|\\s|\\x60|;]|$)"

[[pattern]]
name = "Facebook OAuth"
regex = "EAACEdEose0cBA[0-9A-Za-z]+"

[[pattern]]
name = "Etsy Access Token"
regex = "(?i)(?:etsy)(?:[0-9a-z\\-_\t .]{0,20})(?:[\\s|']|[\\s|\"]){0,3}(?:=|>|:{1,3}=|\\|\\|:|<=|=>|:|\\?=)(?:'|\"|\\s|=|\\x60){0,5}([a-z0-9]{24})(?:['|\"|\n|\r|\\s|\\x60|;]|$)"

[[pattern]]
name = "Facebook Access Token"
regex = "(?i)(?:facebook)(?:[0-9a-z\\-_\t .]{0,20})(?:[\\s|']|[\\s|\"]){0,3}(?:=|>|:{1,3}=|\\|\\|:|<=|=>|:|\\?=)(?:'|\"|\\s|=|\\x60){0,5}([a-f0-9]{32})(?:['|\"|\n|\r|\\s|\\x60|;]|$)"

[[pattern]]
name = "GitHub API Key"
regex = "github(.{0,20})?['\\\"][0-9a-zA-Z]{35,40}"

[[pattern]]
name = "GitHub Access Token"
regex = "github_pat_[0-9a-zA-Z_]{82}"

[[pattern]]
name = "GitHub OAuth"
regex = "gho_[0-9a-zA-Z]{36}"

[[pattern]]
name = "GitHub Personal Access Token"
regex = "ghp_[0-9a-zA-Z]{36}"

[[pattern]]
name = "GitHub Refresh Token"
regex = "ghr_[0-9a-zA-Z]{76}"

[[pattern]]
name = "GitHub User/Server OAuth"
regex = "(ghu|ghs)_[0-9a-zA-Z]{36}"

[[pattern]]
name = "Google API Key"
regex = "AIza[0-9A-Za-z_\\-]{35}"

[[pattern]]
name = "Google Cloud API Key"
regex = "(google|gcp|youtube|drive|yt)(.{0,20})?['\\\"][AIza[0-9a-z_\\-]{35}]['\\\"]"

[[pattern]]
name = "Google Drive OAuth"
regex = "[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com"

[[pattern]]
name = "Google OAuth Access Token"
regex = "ya29\\.[0-9A-Za-z_\\-]+"

[[pattern]]
name = "JSON Web Token"
regex = "(ey[0-9a-z]{30,34}\\.ey[0-9a-z\\/_\\-]{30,}\\.[0-9a-zA-Z\\/_\\-]{10,}={0,2})"

[[pattern]]
name = "LinkedIn Client ID"
regex = "linkedin(.{0,20})?['\\\"][0-9a-z]{12}['\\\"]"

[[pattern]]
name = "LinkedIn Secret Key"
regex = "linkedin(.{0,20})?['\\\"][0-9a-z]{16}['\\\"]"

[[pattern]]
name = "Mapbox API Key"
regex = "(pk\\.[a-z0-9]{60}\\.[a-z0-9]{22})"

[[pattern]]
name = "NPM Access Token"
regex = "(?i)\b(npm_[a-z0-9]{36})(?:['|\"|\n|\r|\\s|\\x60|;]|$)"

[[pattern]]
name = "Pastebin API Key"
regex = "(pastebin[a-z0-9_ \\.,\\-]{0,25})(=|>|:=|\\|\\|:|<=|=>|:).{0,5}['\\\"]([a-z0-9]{32})['\\\"]"

[[pattern]]
name = "Travis CI API Key"
regex = "travis[_\\-]ci(.{0,20})?['\\\"][0-9a-zA-Z]{40}['\\\"]"

[[pattern]]
name = "Trello API Key"
regex = "(trello[a-z0-9_ \\.,\\-]{0,25})(=|>|:=|\\|\\|:|<=|=>|:).{0,5}['\\\"]([0-9a-z]{32})['\\\"]"

[[pattern]]
name = "Twilio API Key"
regex = "SK[0-9a-fA-F]{32}"

[[pattern]]
name = "Twitch API Key"
regex = "(twitch[a-z0-9_ \\.,\\-]{0,25})(=|>|:=|\\|\\|:|<=|=>|:).{0,5}['\\\"]([a-z0-9]{30})['\\\"]"

[[pattern]]
name = "Twitter API Key"
regex = "[tT][wW][iI][tT][tT][eE][rR](.{0,20})?['\\\"][0-9a-z]{18,25}"

[[pattern]]
name = "Twitter Bearer Token"
regex = "(A{22}[a-zA-Z0-9%]{80,100})"

[[pattern]]
name = "Twitter OAuth"
regex = "[tT][wW][iI][tT][tT][eE][rR].{0,30}['\\\"\\\\s][0-9a-zA-Z]{35,44}['\\\"\\\\s]"

[[pattern]]
name = "Twitter Secret Key"
regex = "[tT][wW][iI][tT][tT][eE][rR](.{0,20})?['\\\"][0-9a-z]{35,44}"

[[pattern]]
name = "Yandex API Key"
regex = "(AQVN[A-Za-z0-9_\\-]{35,38})"

[[pattern]]
name = "Yandex Access Token"
regex = "(t1\\.[A-Z0-9a-z_-]+[=]{0,2}\\.[A-Z0-9a-z_-]{86}[=]{0,2})"